### ISSUE TITLE
Adding (all and only correct) categories during upload

### ISSUE THREAD

**Issue by prototyperspective** [bawolff/OWIDImporter#1]
Please make the tool set the correct categories. Except for the many files uploaded presumably with this tool over the last few days all the OWID files are categorized meticulously into various categories and it would be good to keep it that way.

E.g. adding categories like "Charts showing data through 2021" depending on what the latest data point is (user could specify that) or all the relevant Our World in Data subcats. See [here](https://commons.wikimedia.org/wiki/User_talk:Hassan.m.amin#OWID_uploads_with_flawed_categories_set).

**Comment by bawolff** [comment]
Hi, I handed off maintenance of this tool to WikiMed people. I think its best to file this bug at https://github.com/wpmed-videowiki/OWIDImporter which i believe is now the main repo.

**Comment by prototyperspective** [comment]
@bawolff If that is the new / actively-developed repo, could you please link to it from the readme? People will have it even harder finding it and are less likely to find it and may think this is the active repo

@hassanamin994 please enable issues in your repo as also asked [here](https://commons.wikimedia.org/wiki/User_talk:Doc_James#c-Prototyperspective-20250511175000-Doc_James-20250417152700)
